//
//  LButtonStyleKit.swift
//  Pocket Locksmith
//
//  Created by richayden on 8/31/15.
//  Copyright (c) 2015 richayden. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class LButtonStyleKit : NSObject {

    //// Drawing Methods

    public class func drawLButton() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let color = UIColor(red: 0.784, green: 0.788, blue: 0.655, alpha: 1.000)

        //// Bezier 2 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 50, 50)
        CGContextRotateCTM(context, -180 * CGFloat(M_PI) / 180)

        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(17.68, 7.64))
        bezier2Path.addLineToPoint(CGPointMake(15.56, 9.77))
        bezier2Path.addLineToPoint(CGPointMake(31.11, 25.32))
        bezier2Path.addCurveToPoint(CGPointMake(15.56, 40.88), controlPoint1: CGPointMake(26.42, 30.02), controlPoint2: CGPointMake(15.56, 40.88))
        bezier2Path.addCurveToPoint(CGPointMake(17.68, 43), controlPoint1: CGPointMake(15.56, 40.88), controlPoint2: CGPointMake(17.68, 43))
        bezier2Path.addCurveToPoint(CGPointMake(33.23, 27.44), controlPoint1: CGPointMake(17.68, 43), controlPoint2: CGPointMake(28.54, 32.14))
        bezier2Path.addLineToPoint(CGPointMake(35.36, 25.32))
        bezier2Path.addLineToPoint(CGPointMake(17.68, 7.64))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(50, 25))
        bezier2Path.addCurveToPoint(CGPointMake(25, 50), controlPoint1: CGPointMake(50, 38.81), controlPoint2: CGPointMake(38.81, 50))
        bezier2Path.addCurveToPoint(CGPointMake(0, 25), controlPoint1: CGPointMake(11.19, 50), controlPoint2: CGPointMake(0, 38.81))
        bezier2Path.addCurveToPoint(CGPointMake(9.9, 5.08), controlPoint1: CGPointMake(0, 16.87), controlPoint2: CGPointMake(3.88, 9.64))
        bezier2Path.addCurveToPoint(CGPointMake(25, 0), controlPoint1: CGPointMake(14.09, 1.89), controlPoint2: CGPointMake(19.33, 0))
        bezier2Path.addCurveToPoint(CGPointMake(50, 25), controlPoint1: CGPointMake(38.81, 0), controlPoint2: CGPointMake(50, 11.19))
        bezier2Path.closePath()
        color.setFill()
        bezier2Path.fill()

        CGContextRestoreGState(context)
    }

}
